# Generated by Django 5.1.1 on 2024-10-01 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('cafe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitable.cafe')),
                ('candles', models.IntegerField()),
            ],
            bases=('multitable.cafe',),
        ),
        migrations.CreateModel(
            name='ColdDrink',
            fields=[
                ('cafe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='multitable.cafe')),
                ('straw', models.BooleanField()),
            ],
            bases=('multitable.cafe',),
        ),
    ]
